# permissions for end users to edit icanhazlbservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: icanhazlbservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: icanhazlbservice-editor-role
rules:
- apiGroups:
  - service.icanhazlb.com
  resources:
  - icanhazlbservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.icanhazlb.com
  resources:
  - icanhazlbservices/status
  verbs:
  - get
