---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - service.icanhazlb.com
  resources:
  - icanhazlbservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.icanhazlb.com
  resources:
  - icanhazlbservices/finalizers
  verbs:
  - update
- apiGroups:
  - service.icanhazlb.com
  resources:
  - icanhazlbservices/status
  verbs:
  - get
  - patch
  - update
