---
apiVersion: service.icanhazlb.com/v1alpha1
kind: IcanhazlbService
metadata:
  name: icanhazlb-example
  namespace: default
spec:
  endpointSlices:
    name: icanhazlb-example-svc
    addressType: IPv4
    ports:
      - name: http
        port: 80
    endpoints:
      - addresses:
        - 1.2.3.4
    labels:
      kubernetes.io/service-name: icanhazlb-example-svc
  services:
    name: icanhazlb-example-svc
    type: ClusterIP
    ipFamilies:
    - IPv4
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
    labels:
      kubernetes.io/service-name: icanhazlb-example-svc
  ingresses:
    name: icanhazlb-example-ing
    annotations:
      nginx.ingress.kubernetes.io/upstream-vhost: example.domain.com
    ingressClassName: nginx
    rules:
    - host: example.icanhazlb.com
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: icanhazlb-example-svc
              port:
                number: 80
